### ISSUE TITLE
How did you get your VM? 

### ISSUE THREAD

**Issue by VehementHam** [ChrisTitusTech/hyprland-titus#14]
Can I have the script for your VM?

**Comment by ChrisTitusTech** [comment]
Sadly I wasn't able to get this setup in a VM. I've only run it on bare metal.

**Comment by VehementHam** [comment]
No, I mean how did you get the Windows WM working like that? What was your script for opening it?

**Comment by ChrisTitusTech** [comment]
Looking Glass and then just launching it via a command hotkey in the hyprland.conf. 

> No, I mean how did you get the Windows WM working like that? What was your script for opening it?

**Comment by ruohki** [comment]
i think he is talking about `/home/titus/w11` script - also interested in this

**Comment by D3vil0p3r** [comment]
Indeed. @ChrisTitusTech in your `hyperland.conf` there is a:
```
bind = SUPER, L, exec, /home/titus/w11
```
what is it used for? Is it possible to have the source file?
