### ISSUE TITLE
Artifacts on VM (QEMU/KVM) 

### ISSUE THREAD

**Issue by korayoezdemir** [ChrisTitusTech/hyprland-titus#34]
Hi there, 

I wanted to try your desktop for myself and tried to install it in a VM. 

After archinstall dektop install with sway, the guest performace was super poor with a lot of artifacts and black screening. 

Is this related to my system of to wayland itself?

**Comment by ChrisTitusTech** [comment]
Hyprland isn't meant to run in a VM per the developer of it. He is still working on this compatibility.
