### ISSUE TITLE
Which cursor theme is used in this rice ?

### ISSUE THREAD

**Issue by MrDisguised** [ChrisTitusTech/hyprland-titus#37]
This is not an issue but I wanted to know which cursor theme is used in this rice. I am 100 % sure that it is not Breeze cursor. It would mean a lot to me if I can know the cursor theme name so that I can use in my rice :P .

**Comment by Velosofy** [comment]
Adwaita cursor

**Comment by MrDisguised** [comment]
> Adwaita cursor

I just watched [chris titus's hyprland video](https://www.youtube.com/watch?v=wNL6eIoksd8) and I don't think this is an Adwaita cursor. Here are the pics - <br>
![image](https://github.com/ChrisTitusTech/hyprland-titus/assets/128170542/5b34a889-9638-44db-a03f-c74d03ed357d)
<br>
![image](https://github.com/ChrisTitusTech/hyprland-titus/assets/128170542/78597e9b-e629-4827-9327-12f41128d450)

EDIT: It is not a Breeze cursor.

**Comment by MrDisguised** [comment]
> Ah my bad, I believe its [Nordzy](https://github.com/alvatip/Nordzy-cursors)

thanks a lot :P :D
